Document: pocket-home
Title: Debian pocket-home Manual
Author: <insert document author here>
Abstract: This manual describes what pocket-home is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pocket-home/pocket-home.sgml.gz

Format: postscript
Files: /usr/share/doc/pocket-home/pocket-home.ps.gz

Format: text
Files: /usr/share/doc/pocket-home/pocket-home.text.gz

Format: HTML
Index: /usr/share/doc/pocket-home/html/index.html
Files: /usr/share/doc/pocket-home/html/*.html
